### ISSUE TITLE
Project Checklist

### ISSUE THREAD

**Issue by aayushsss1** [aayushsss1/WikiSpeaks#2]
- [x] KServe  Llama deployment
- [x] Wikipedia API 
- [x] Persisting in Faiss using ray
- [x] Prompt using OpenAI API Client for vLLM runtimes
- [x] Streamlit UI
- [x] Monitoring
